### ISSUE TITLE
TemplateProcessingException when using #jawr.imagePath

### ISSUE THREAD

**Issue by ptahchiev** [dtrunk90/thymeleaf-jawr-extension#11]
Hello,

here's my html:
````
<span th:with="imgUrl=${#jawr.imagePath('/resources/theme/solarapparel/normal/img/icon-gift.png')}" style="position: absolute; right: 10px; bottom: 10px; width: 60px; height: 60px; background: #ececec url(${imgUrl}) 50% 50% no-repeat; border-radius: 50%;"></span>
````
and when I try to render the page I get this exception:
````
org.thymeleaf.exceptions.TemplateProcessingException: Handler "net.jawr.web.resource.bundle.BINARY_CONTEXT_ATTRIBUTE" not present in servlet context. Initialization of Jawr either failed or never occurred. (solar/basic_two_column.html:107)
	at com.github.dtrunk90.thymeleaf.jawr.util.ContextUtils.getHandlerFromContext(ContextUtils.java:11)
	at com.github.dtrunk90.thymeleaf.jawr.expression.Jawr.imagePath(Jawr.java:23)
	at com.github.dtrunk90.thymeleaf.jawr.expression.Jawr.imagePath(Jawr.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:113)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:102)
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49)
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:347)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:267)
	at org.thymeleaf.spring4.expression.SpelVariableExpressionEvaluator.evaluate(SpelVariableExpressionEvaluator.java:139)
	at org.thymeleaf.standard.expression.VariableExpression.executeVariable(VariableExpression.java:154)
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:59)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:103)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:133)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:120)
	at org.thymeleaf.standard.processor.attr.AbstractStandardLocalVariableDefinitionAttrProcessor.getNewLocalVariables(AbstractStandardLocalVariableDefinitionAttrProcessor.java:89)
	at org.thymeleaf.processor.attr.AbstractLocalVariableDefinitionAttrProcessor.processAttribute(AbstractLocalVariableDefinitionAttrProcessor.java:62)
	at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:87)
	at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
	at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:1017)
	at org.thymeleaf.dom.Node.processNode(Node.java:972)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.Document.process(Document.java:93)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1155)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:924)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:898)
````

I use this bean:

````
    @Bean(name = { "thymeleafEmailTemplateEngine", "emailTemplateEngine" })
    public SpringTemplateEngine thymeleafEmailTemplateEngine(@Qualifier("nemesisDialect") IDialect nemesisDialect) {
        final SpringTemplateEngine templateEngine = new SpringTemplateEngine();
        templateEngine.addTemplateResolver(thymeleafSpringResourceTemplateResolver());
        templateEngine.addTemplateResolver(thymeleafClasspathTemplateResolver());
        templateEngine.addTemplateResolver(thymeleafServletTemplateResolver());
        //            templateEngine.addTemplateResolver(thymeleafInMemoryTemplateResolver());
        Set<IDialect> dialects = new LinkedHashSet<>();
        dialects.add(nemesisDialect);
        dialects.add(defaultJawrDialect());
        templateEngine.setAdditionalDialects(dialects);

        return templateEngine;
    }
````

which then I inject and use like this:
````
getTemplateEngine().process(templateName, ctx);
````

**Comment by dtrunk90** [comment]
How did you configured Jawr itself? In your case you need to create jawr spring controller beans as described [here](https://jawr.java.net/integration/spring.html).

**Comment by ptahchiev** [comment]
Yes, that's the thing.

I have the jawr controllers configured:

````
    /* JAWR */

    protected JawrSpringController defaultJawrSpringController(final String type) {
        final JawrSpringController controller = new JawrSpringController();
        if (applicationContext instanceof WebApplicationContext) {
            controller.setServletContext(((WebApplicationContext) applicationContext).getServletContext());

            final Properties props = new Properties();

            //props.setProperty("jawr.css.skin.default.root.dirs", "/css/skins/");

            props.setProperty("jawr.debug.on", String.valueOf(BooleanUtils.isTrue(jawrProperties.getDebug())));
            props.setProperty("jawr.gzip.on", String.valueOf(BooleanUtils.isTrue(jawrProperties.getGzip())));
            props.setProperty("jawr.gzip.ie6.on", String.valueOf(BooleanUtils.isTrue(jawrProperties.getGzipIE6())));
            props.setProperty("jawr.charset.name", jawrProperties.getCharset());

            props.setProperty("jawr.js.commonURLPrefix", "/resources/js/");
            props.setProperty("jawr.js.bundle.basedir", "/resources/theme");

            props.setProperty("jawr.css.commonURLPrefix", "/resources/css/");
            props.setProperty("jawr.css.bundle.basedir", "/resources/theme");
            //props.setProperty("jawr.css.bundle.factory.global.preprocessors", "smartsprites");

            Map<String, JawrPropertyProvider> result = applicationContext.getBeansOfType(JawrPropertyProvider.class);
            for (Map.Entry<String, JawrPropertyProvider> e : result.entrySet()) {
                Properties properties = e.getValue().provideJawrProperties();
                if (applicationContext instanceof ConfigurableApplicationContext) {
                    for (String key : properties.stringPropertyNames()) {
                        String value = ((ConfigurableApplicationContext) applicationContext).getBeanFactory().resolveEmbeddedValue(properties.getProperty(key));
                        props.setProperty(key, value);
                    }
                } else {
                    props.putAll(properties);
                }
            }

            controller.setConfiguration(props);
            controller.setType(type);
        }

        return controller;
    }

    @Bean(name = "jawrJsController")
    protected JawrSpringController jawrJsController() {
        return defaultJawrSpringController(JawrConstant.JS_TYPE);
    }

    @Bean(name = "jawrImageController")
    protected JawrSpringController jawrImageController() {
        return defaultJawrSpringController(JawrConstant.BINARY_TYPE);
    }

    @Bean(name = "jawrCssController")
    protected JawrSpringController jawrCssController() {
        return defaultJawrSpringController(JawrConstant.CSS_TYPE);
    }
````

Also notice that `jawr:src` and `jawr:href` works fine, even with the older version.

**Comment by dtrunk90** [comment]
It's new to me to set the servlet context manually: `controller.setServletContext(((WebApplicationContext) applicationContext).getServletContext());`

You can take a look at this [spring boot autoconfiguration](https://github.com/ic3fox/jawr-main-repo/blob/master/jawr-spring/jawr-spring-extension/src/main/java/net/jawr/web/autoconfigure/JawrAutoConfiguration.java).

Do you have a reproduction code for me? Then I can take a look at it.

If the code shouldn't be public you can also send it by mail: dtrunk90@gmail.com

**Comment by ptahchiev** [comment]
Hi Danny,

this `JawrAutoConfiguration.java` is not release yet, isn't it? I'll try to create a reproduceable test-case.

**Comment by dtrunk90** [comment]
No it's not released yet. That would be great. Thanks.

**Comment by dtrunk90** [comment]
I've made small reproduction: https://github.com/dtrunk90/thymeleaf-jawr-11
I'll take a look at it asap

**Comment by dtrunk90** [comment]
The exception seems to occur if the jawr dialect isn't initialized correctly. Maybe you have to add `@Bean` annotation to be spring managed. Can you show me the full `defaultJawrDialect()` method (including annotations)?

The above mentioned repository has a working example using Spring Boot (incl. auto configuration of the jawr dialect which simply adds a spring bean: [JawrThymeleafAutoConfiguration.java](https://github.com/dtrunk90/thymeleaf-jawr-extension/blob/master/src/main/java/com/github/dtrunk90/thymeleaf/jawr/autoconfigure/JawrThymeleafAutoConfiguration.java).

I've seen this exception when I forgot to initialize the Dialect.

**Comment by dtrunk90** [comment]
@ptahchiev Any news here?

**Comment by ptahchiev** [comment]
Yes, sorry I will close this issue. Turned out we were creating a `MockServletContext` before programmatically calling parse.
