### ISSUE TITLE
Upgrade to jawr 3.9

### ISSUE THREAD

**Issue by ptahchiev** [dtrunk90/thymeleaf-jawr-extension#12]
Hi there,

with jawr 3.9 I get the following error:

````
2016-08-24 18:17:33,545 org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/storefront].[dispatcherServlet] [http-nio-127.0.0.1-8112-exec-3] ERROR: Servlet.service() for servlet [dispatcherServlet] in context with path [/storefront] threw exception [Handler processing failed; nested exception is java.lang.NoSuchMethodError: net.jawr.web.resource.bundle.renderer.RendererFactory.getJsBundleRenderer(Lnet/jawr/web/resource/bundle/handler/ResourceBundlesHandler;Ljava/lang/Boolean;Ljava/lang/Boolean;Ljava/lang/Boolean;)Lnet/jawr/web/resource/bundle/renderer/JsBundleLinkRenderer;] with root cause
java.lang.NoSuchMethodError: net.jawr.web.resource.bundle.renderer.RendererFactory.getJsBundleRenderer(Lnet/jawr/web/resource/bundle/handler/ResourceBundlesHandler;Ljava/lang/Boolean;Ljava/lang/Boolean;Ljava/lang/Boolean;)Lnet/jawr/web/resource/bundle/renderer/JsBundleLinkRenderer;
	at com.github.dtrunk90.thymeleaf.jawr.processor.attr.impl.js.JawrJsElementSubstitutionAttrProcessor.render(JawrJsElementSubstitutionAttrProcessor.java:42)
	at com.github.dtrunk90.thymeleaf.jawr.processor.attr.AbstractJawrElementSubstitutionAttrProcessor.getText(AbstractJawrElementSubstitutionAttrProcessor.java:38)
	at org.thymeleaf.processor.attr.AbstractUnescapedTextChildModifierAttrProcessor.getModifiedChildren(AbstractUnescapedTextChildModifierAttrProcessor.java:60)
	at org.thymeleaf.processor.attr.AbstractChildrenModifierAttrProcessor.processAttribute(AbstractChildrenModifierAttrProcessor.java:59)
````

And indeed the signature of this method `RendererFactory.getJsBundleRenderer` has been changed. Please update to jawr 3.9

**Comment by dtrunk90** [comment]
Oh, I've really missed the release of 3.9.
I've already made a branch for it months ago.

Thank you. I'll work on it asap.

**Comment by dtrunk90** [comment]
Version 2.0.1 is released

**Comment by ptahchiev** [comment]
Is it possible to backport to 1.2.1 branch too?

**Comment by dtrunk90** [comment]
Why? Are you still using Thymeleaf 2?

**Comment by ptahchiev** [comment]
Unfortunately yes, we have some issues migrating our custom dialect to thymeleaf3 and it will be some months before we are able to upgrade. I think there might be other people in the same situation too.

**Comment by dtrunk90** [comment]
Then I'll do my best to recover the code and backport it.

**Comment by dtrunk90** [comment]
Version 1.2.1 is released.
