### ISSUE TITLE
SpringBoot with Thymeleaf and JAWR

### ISSUE THREAD

**Issue by csgruenebe** [dtrunk90/thymeleaf-jawr-extension#3]
Hello,

Could you please have a look at my demo application. I am trying to use the thymeleaf-jawr-extension,
but it does not seem to work.

I use spring boot and my templates and static files reside in /src/main/resources/. Due to deployment to heroku and other cloud services we don't have /src/main/webapp/ anymore. This is also a best practice from the spring boot doc.

Here is my application:
https://github.com/comsysto/spring-boot-js-css-bundle-demo/tree/jawr-question/spring-boot-thymeleaf-jawr

In the **[templates/angularApp.html](
https://github.com/comsysto/spring-boot-js-css-bundle-demo/blob/master/spring-boot-thymeleaf-jawr/src/main/resources/templates/angularApp.html)**  I use the following statements:
```
<link jawr:style="/css/webjars.css" />
<script jawr:script="/js/webjars.js" src="#"></script>
```
But when Spring Boot starts up there is an exception:
```
12:27:06.740 [http-nio-8080-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Could not parse as expression: "/css/webjars.css" (angularApp:18)] with root cause
org.thymeleaf.exceptions.TemplateProcessingException: Could not parse as expression: "/css/webjars.css" (angularApp:18)
	at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:238) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:79) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:40) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at com.github.dtrunk90.thymeleaf.jawr.AbstractJawrAttrProcessor.getText(AbstractJawrAttrProcessor.java:49) ~[thymeleaf-jawr-extension-1.0.1.jar:na]
	at org.thymeleaf.processor.attr.AbstractUnescapedTextChildModifierAttrProcessor.getModifiedChildren(AbstractUnescapedTextChildModifierAttrProcessor.java:60) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.thymeleaf.processor.attr.AbstractChildrenModifierAttrProcessor.processAttribute(AbstractChildrenModifierAttrProcessor.java:59) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at com.github.dtrunk90.thymeleaf.jawr.JawrTagRemovingAttrProcessor.processAttribute(JawrTagRemovingAttrProcessor.java:34) ~[thymeleaf-jawr-extension-1.0.1.jar:na]
```

I added the Dialect to the template Engine in: **[WebAppConfig.java](https://github.com/comsysto/spring-boot-js-css-bundle-demo/blob/master/spring-boot-thymeleaf-jawr/src/main/groovy/com/comsysto/springdemo/webapp/WebAppConfig.java)**

But something is not right. There are also the JAWR Spring Controllers here: **[webapp/jawr](https://github.com/comsysto/spring-boot-js-css-bundle-demo/tree/master/spring-boot-thymeleaf-jawr/src/main/groovy/com/comsysto/springdemo/webapp/jawr)**

Could you please tell me what I am doing wrong. Thanks in advance :)

**Comment by dtrunk90** [comment]
Try `<link jawr:style="'/css/webjars.css'" />` instead of `<link jawr:style="/css/webjars.css" />` and `<script jawr:script="'/js/webjars.js'" src="#"></script>` instead of `<script jawr:script="/js/webjars.js" src="#"></script>` (notice the `'` at beginning and end of the attribute values).

This is what the Exception already says: `Could not parse as expression: "/css/webjars.css"`

See #1 for reference

Pls close if it works for you

**Comment by csgruenebe** [comment]
works like a charm :+1: 
thanks a lot

**Comment by dtrunk90** [comment]
You can update to the latest version (1.1.1) to remove the single quotes again. Also notice the new and changed attribute names.
