### ISSUE TITLE
NoSuchMethodError: JawrConfig.getJsBundleLinkRenderClass()

### ISSUE THREAD

**Issue by koolfreak** [dtrunk90/thymeleaf-jawr-extension#8]
```
java.lang.NoSuchMethodError: net.jawr.web.config.JawrConfig.getJsBundleLinkRenderClass()Ljava/lang/String;
	at net.jawr.web.resource.bundle.renderer.RendererFactory.getJsBundleRenderer(RendererFactory.java:46) ~[jawr-core-3.7.jar:na]
	at com.github.dtrunk90.thymeleaf.jawr.processor.attr.impl.js.JawrJsElementSubstitutionAttrProcessor.render(JawrJsElementSubstitutionAttrProcessor.java:39) ~[thymeleaf-jawr-extension-1.1.1.jar:na]
	at com.github.dtrunk90.thymeleaf.jawr.processor.attr.AbstractJawrElementSubstitutionAttrProcessor.getText(AbstractJawrElementSubstitutionAttrProcessor.java:38) ~[thymeleaf-jawr-extension-1.1.1.jar:na]
	at org.thymeleaf.processor.attr.AbstractUnescapedTextChildModifierAttrProcessor.getModifiedChildren(AbstractUnescapedTextChildModifierAttrProcessor.java:60) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.thymeleaf.processor.attr.AbstractChildrenModifierAttrProcessor.processAttribute(AbstractChildrenModifierAttrProcessor.java:59) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:87) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:1017) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.thymeleaf.dom.Node.processNode(Node.java:972) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.thymeleaf.dom.Node.processNode(Node.java:990) ~[thymeleaf-2.1.4.RELEASE.jar:2.1.4.RELEASE]
```

**Comment by dtrunk90** [comment]
Could you provide more information please? Which version of Jawr are you using? Is Jawr in your classpath? If you are using maven it would be great to provide the output of `mvn dependency:tree -Dverbose`.

**Comment by koolfreak** [comment]
Hi,
Hope this helps..I dont have currently the workspace with me now.
 
<dependency>
            <groupId>net.jawr</groupId>
            <artifactId>jawr</artifactId>
            <version>3.3.3</version>
        </dependency>

<dependency>
			<groupId>org.thymeleaf</groupId>
			<artifactId>thymeleaf</artifactId>
			<version>2.1.4.RELEASE</version>
		</dependency>

jawr-core-3.7.jar
spring mvc - 3.2.16.RELEASE

**Comment by koolfreak** [comment]
jawr.debug.overrideKey=jawrR3fr35hK3y
jawr.config.reload.refreshKey=jawrR3fr35hK3y

# Javascript properties and mappings
jawr.js.bundle.basedir=/js

# All files within /js/lib will be together in a bundle.
# The remaining scripts will be served sepparately.
jawr.js.bundle.lib.id=/bundles/lib.js
jawr.js.bundle.lib.mappings=/js/core/jquery-1.10.2.min.js
#jawr.js.bundle.lib.global=true
#jawr.js.bundle.lib.order=1
==============================


    <bean abstract="true" id="jawrBase" class="net.jawr.web.servlet.JawrSpringController">
        <property name="configLocation" value="/jawr.properties" />
        <property name="configuration">
            <props>
                <prop key="jawr.debug.on">true</prop> 
                <prop key="jawr.gzip.on">false</prop> 
            </props>
        </property>
    </bean>

	
	<bean id="jawrJsController" parent="jawrBase" />

	
	

    <bean id="urlMapping"
          class="org.springframework.web.servlet.handler.SimpleUrlHandlerMapping">
        <property name="mappings">
            <props>
                <prop key="/**/*.js">jawrJsController</prop>
                
            </props>
        </property>
    </bean>

**Comment by dtrunk90** [comment]
It seems your webapp is using an old jawr version (3.3.3). Make sure to have at least Jawr 3.5 (better current; 3.8). The missing method is available since Jawr 3.5. Just cleanup your classpath.

**Comment by koolfreak** [comment]
ok...will try it and give you feedback

**Comment by koolfreak** [comment]
yeah updating to 3.8 solve the problem. it now becomes net.jawr:jawr-core:3.8 and also if using spring you need also a jawr spring extension.

thanks
